name: curate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
#version: 1.1.0+14
version: 1.1.2+17

environment:
  sdk: '>=2.18.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  dio: ^5.0.3
  photo_view: ^0.15.0
  #package_info_plus: ^4.0.0
  path_provider: ^2.0.11
  url_launcher: ^6.1.3
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  awesome_dialog: ^3.2.1
  get_it: ^8.0.3
  logger: ^2.5.0
  sizer: ^3.0.5
  device_info_plus: ^11.2.0
  platform_device_id: ^1.0.1
  timeago: ^3.3.0
  chewie: ^1.3.0
  provider: ^6.0.4
  google_fonts: ^6.2.1
  page_transition: ^2.0.9
  chucker_flutter: ^1.5.1
  path_drawing: ^1.0.1

  dropdown_button2: ^2.3.9
  animated_toggle_switch: ^0.8.4
  badges: ^3.1.2
  another_flushbar: ^1.12.29
  loader_overlay: ^4.0.3
  flag: ^7.0.0
  mime: ^2.0.0
  file_picker: ^8.1.6
  dots_indicator: ^3.0.0
  otp_text_field: ^1.1.3
  fl_country_code_picker: ^0.1.9+1
  http: ^1.2.2
  http_parser: ^4.0.2
  lottie: ^3.3.0
  country_picker: ^2.0.17
  change_app_package_name: ^1.1.0
  double_back_to_close_app: ^2.1.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  connectivity_plus: ^6.1.1
  flutter_html: ^3.0.0-alpha.6
  infinite_scroll_pagination: ^4.1.0
  readmore: ^3.0.0
  scrollable_positioned_list: ^0.3.7
  custom_refresh_indicator: ^4.0.1
  flutter_svg: ^2.0.16
  simple_circular_progress_bar: ^1.0.2
  percent_indicator: ^4.2.3
  open_filex: ^4.3.2
  vibration: ^2.0.1
  roundcheckbox: ^2.0.5
  at_gauges: ^1.0.1
  custom_navigation_bar: ^0.8.2
  fl_chart: ^0.70.0  
  youtube_player_flutter: ^9.1.1
  loop_page_view: ^1.2.1
  calendar_date_picker2: ^1.1.8
  shimmer: ^3.0.0
  firebase_core: ^3.9.0
  firebase_analytics: ^11.3.6
  flutter_profile_picture: ^2.0.0
  firebase_crashlytics: ^4.2.0
  pinput: ^5.0.0
  socket_io_client: ^3.0.2
  package_info_plus: ^8.1.2
  progressive_image: ^2.0.0
  app_settings: ^5.1.1
  webview_flutter: ^4.2.2
  in_app_purchase: ^3.1.10
  app_store_server_sdk: ^1.2.7
  device_imei: ^0.0.4+2




dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/ic_launcher.png"
  adaptive_icon_background: "#9795bd"
  adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.png"
  image_path_ios: "assets/icon/ic_launcher_ios.png"
  min_sdk_android: 21
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/svg/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from